<?php

/**
 * @file
 * Contains brewery.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function brewery_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the brewery module.
    case 'help.page.brewery':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A brewery in a module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function brewery_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_toolbar()
 */
function brewery_toolbar() {
  $items = [];

  $links = array(
    'products' => array(
      '#type' => 'link',
      '#title' => t('All products'),
      '#url' => Url::fromRoute('entity.brewery_product.collection'),
    ),
    'product_types' => array(
      '#type' => 'link',
      '#title' => t('Product types'),
      '#url' => Url::fromRoute('entity.brewery_product_type.collection'),
    ),
    'product_styles' => array(
      '#type' => 'link',
      '#title' => t('Product styles'),
      '#url' => Url::fromRoute('entity.brewery_style.collection'),
    ),
  );

  $items['brewery'] = [
    '#type' => 'toolbar_item',
    '#weight' => 100,
    'tab' => [
      '#type' => 'link',
      '#title' => t('Brewery'),
      '#url' => Url::fromRoute('entity.brewery_product.collection'),
      '#attributes' => [
        'title' => t('Brewery settings'),
        'class' => ['toolbar-icon', 'toolbar-icon-menu'],
      ],
    ],
    'tray' => [
      '#theme' => 'item_list',
      '#items' => $links,
      '#attributes' => [
        'class' => array('toolbar-menu'),
      ],
    ]
  ];

  return $items;
}
