<?php

/**
 * @file
 * Contains brewery.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function brewery_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the brewery module.
    case 'help.page.brewery':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A brewery in a module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function brewery_theme() {
  $theme = [];

  return $theme;
}
