
# Product routing definition
entity.brewery_product.canonical:
  path: '/admin/brewery_product/{brewery_product}'
  defaults:
    _entity_view: 'brewery_product'
    _title: 'Product'
  requirements:
    _entity_access: 'brewery_product.view'
  options:
    _admin_route: TRUE

entity.brewery_product.collection:
  path: '/admin/brewery_product'
  defaults:
    _entity_list: 'brewery_product'
    _title: 'Product list'
  requirements:
    _permission: 'view product entities'
  options:
    _admin_route: TRUE

entity.brewery_product.add_form:
  path: '/admin/brewery_product/add'
  defaults:
    _entity_form: brewery_product.add
    _title: 'Add Product'
  requirements:
    _permission: 'add product entities'
  options:
    _admin_route: TRUE

entity.brewery_product.edit_form:
  path: '/admin/brewery_product/{brewery_product}/edit'
  defaults:
    _entity_form: brewery_product.edit
    _title: 'Edit Product'
  requirements:
    _permission: 'edit product entities'
  options:
    _admin_route: TRUE

entity.brewery_product.delete_form:
  path: '/admin/brewery_product/{brewery_product}/delete'
  defaults:
    _entity_form: brewery_product.delete
    _title: 'Delete Product'
  requirements:
    _permission: 'delete product entities'
  options:
    _admin_route: TRUE

brewery_product.settings:
  path: 'admin/structure/brewery_product'
  defaults:
   _form: '\Drupal\product\Entity\Form\ProductSettingsForm'
   _title: 'Product settings'
  requirements:
    _permission: 'administer product entities'
  options:
    _admin_route: TRUE


# ProductType routing definition
entity.brewery_product_type.canonical:
  path: '/admin/brewery_product_type/{brewery_product_type}'
  defaults:
    _entity_view: 'brewery_product_type'
    _title: 'Product type'
  requirements:
    _entity_access: 'brewery_product_type.view'
  options:
    _admin_route: TRUE

entity.brewery_product_type.collection:
  path: '/admin/brewery_product_type'
  defaults:
    _entity_list: 'brewery_product_type'
    _title: 'Product type list'
  requirements:
    _permission: 'view product type entities'
  options:
    _admin_route: TRUE

entity.brewery_product_type.add_form:
  path: '/admin/brewery_product_type/add'
  defaults:
    _entity_form: brewery_product_type.add
    _title: 'Add Product type'
  requirements:
    _permission: 'add product type entities'
  options:
    _admin_route: TRUE

entity.brewery_product_type.edit_form:
  path: '/admin/brewery_product_type/{brewery_product_type}/edit'
  defaults:
    _entity_form: brewery_product_type.edit
    _title: 'Edit Product type'
  requirements:
    _permission: 'edit product type entities'
  options:
    _admin_route: TRUE

entity.brewery_product_type.delete_form:
  path: '/admin/brewery_product_type/{brewery_product_type}/delete'
  defaults:
    _entity_form: brewery_product_type.delete
    _title: 'Delete Product type'
  requirements:
    _permission: 'delete product type entities'
  options:
    _admin_route: TRUE

brewery_product_type.settings:
  path: 'admin/structure/brewery_product_type'
  defaults:
   _form: '\Drupal\product\Entity\Form\ProductTypeSettingsForm'
   _title: 'Product type settings'
  requirements:
    _permission: 'administer product type entities'
  options:
    _admin_route: TRUE


# Style routing definition
entity.brewery_style.canonical:
  path: '/admin/brewery_style/{brewery_style}'
  defaults:
    _entity_view: 'brewery_style'
    _title: 'Style'
  requirements:
    _entity_access: 'brewery_style.view'
  options:
    _admin_route: TRUE

entity.brewery_style.collection:
  path: '/admin/brewery_style'
  defaults:
    _entity_list: 'brewery_style'
    _title: 'Style list'
  requirements:
    _permission: 'view style entities'
  options:
    _admin_route: TRUE

entity.brewery_style.add_form:
  path: '/admin/brewery_style/add'
  defaults:
    _entity_form: brewery_style.add
    _title: 'Add Style'
  requirements:
    _permission: 'add style entities'
  options:
    _admin_route: TRUE

entity.brewery_style.edit_form:
  path: '/admin/brewery_style/{brewery_style}/edit'
  defaults:
    _entity_form: brewery_style.edit
    _title: 'Edit Style'
  requirements:
    _permission: 'edit style entities'
  options:
    _admin_route: TRUE

entity.brewery_style.delete_form:
  path: '/admin/brewery_style/{brewery_style}/delete'
  defaults:
    _entity_form: brewery_style.delete
    _title: 'Delete Style'
  requirements:
    _permission: 'delete style entities'
  options:
    _admin_route: TRUE

brewery_style.settings:
  path: 'admin/structure/brewery_style'
  defaults:
   _form: '\Drupal\product\Entity\Form\StyleSettingsForm'
   _title: 'Style settings'
  requirements:
    _permission: 'administer style entities'
  options:
    _admin_route: TRUE

