add product entities:
  title: 'Create new Product entities'

administer product entities:
  title: 'Administer Product entities'
  description: 'Allow to access the administration form to configure Product entities.'

delete product entities:
  title: 'Delete Product entities'

edit product entities:
  title: 'Edit Product entities'

view product entities:
  title: 'View Product entities'
add product type entities:
  title: 'Create new Product type entities'

administer product type entities:
  title: 'Administer Product type entities'
  description: 'Allow to access the administration form to configure Product type entities.'

delete product type entities:
  title: 'Delete Product type entities'

edit product type entities:
  title: 'Edit Product type entities'

view product type entities:
  title: 'View Product type entities'
add style entities:
  title: 'Create new Style entities'

administer style entities:
  title: 'Administer Style entities'
  description: 'Allow to access the administration form to configure Style entities.'

delete style entities:
  title: 'Delete Style entities'

edit style entities:
  title: 'Edit Style entities'

view style entities:
  title: 'View Style entities'
