# Product menu items definition
entity.brewery_product.collection:
  title: 'Product list'
  route_name: entity.brewery_product.collection
  description: 'List Product entities'

brewery_product.admin.structure.settings:
  title: Product settings
  description: 'Configure Product entities'
  route_name: brewery_product.settings
  parent: system.admin_structure

# Product type menu items definition
entity.brewery_product_type.collection:
  title: 'Product type list'
  route_name: entity.brewery_product_type.collection
  description: 'List Product type entities'

brewery_product_type.admin.structure.settings:
  title: Product type settings
  description: 'Configure Product type entities'
  route_name: brewery_product_type.settings
  parent: system.admin_structure

# Style menu items definition
entity.brewery_style.collection:
  title: 'Style list'
  route_name: entity.brewery_style.collection
  description: 'List Style entities'

brewery_style.admin.structure.settings:
  title: Style settings
  description: 'Configure Style entities'
  route_name: brewery_style.settings
  parent: system.admin_structure

