# Product routing definition
brewery_product.settings_tab:
  route_name: brewery_product.settings
  title: 'Settings'
  base_route: brewery_product.settings

entity.brewery_product.canonical:
  route_name: entity.brewery_product.canonical
  base_route: entity.brewery_product.canonical
  title: 'View'

entity.brewery_product.edit_form:
  route_name: entity.brewery_product.edit_form
  base_route: entity.brewery_product.canonical
  title: Edit

entity.brewery_product.delete_form:
  route_name:  entity.brewery_product.delete_form
  base_route:  entity.brewery_product.canonical
  title: Delete
  weight: 10

# Product type routing definition
brewery_product_type.settings_tab:
  route_name: brewery_product_type.settings
  title: 'Settings'
  base_route: brewery_product_type.settings

entity.brewery_product_type.canonical:
  route_name: entity.brewery_product_type.canonical
  base_route: entity.brewery_product_type.canonical
  title: 'View'

entity.brewery_product_type.edit_form:
  route_name: entity.brewery_product_type.edit_form
  base_route: entity.brewery_product_type.canonical
  title: Edit

entity.brewery_product_type.delete_form:
  route_name:  entity.brewery_product_type.delete_form
  base_route:  entity.brewery_product_type.canonical
  title: Delete
  weight: 10

# Style routing definition
brewery_style.settings_tab:
  route_name: brewery_style.settings
  title: 'Settings'
  base_route: brewery_style.settings

entity.brewery_style.canonical:
  route_name: entity.brewery_style.canonical
  base_route: entity.brewery_style.canonical
  title: 'View'

entity.brewery_style.edit_form:
  route_name: entity.brewery_style.edit_form
  base_route: entity.brewery_style.canonical
  title: Edit

entity.brewery_style.delete_form:
  route_name:  entity.brewery_style.delete_form
  base_route:  entity.brewery_style.canonical
  title: Delete
  weight: 10

