entity.brewery_product.add_form:
  route_name: entity.brewery_product.add_form
  title: 'Add Product'
  appears_on:
    - entity.brewery_product.collection
    - entity.brewery_product.canonical

entity.brewery_product_type.add_form:
  route_name: entity.brewery_product_type.add_form
  title: 'Add Product type'
  appears_on:
    - entity.brewery_product_type.collection
    - entity.brewery_product_type.canonical

entity.brewery_style.add_form:
  route_name: entity.brewery_style.add_form
  title: 'Add Style'
  appears_on:
    - entity.brewery_style.collection
    - entity.brewery_style.canonical

